### ISSUE TITLE
嗨，这个提供的数据集链接已经失效了，您这边能提供一下那个数据集吗

### ISSUE THREAD

**Issue by dejavu6** [foamliu/Transformer#2]

**Comment by ztl-35** [comment]
you can download this dataset in this link.(https://blog.csdn.net/weixin_30883311/article/details/99034425)

**Comment by ztl-35** [comment]
> _No description provided._

you can download this dataset in this link.(https://blog.csdn.net/weixin_30883311/article/details/99034425)

**Comment by foamliu** [comment]
Thanks @ztl-35 .
