### ISSUE TITLE
您好，文中的训练好的模型链接挂了，能重新分享一下吗

### ISSUE THREAD

**Issue by YusenL** [foamliu/Transformer#3]

**Comment by BetterZH** [comment]
同求，可以分享下预训练模型吗

**Comment by Jcek** [comment]
同求，可以分享下预训练好的模型吗

**Comment by zhangxiaoyuan1988** [comment]
大佬，能分享下数据集吗？学习用

**Comment by ARES3366** [comment]
大佬，能分享下数据集吗？学习用，1010276502@qq.com

**Comment by Jcek** [comment]
您好，VG数据集太大，您可以去VG官网下载！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "foamliu/Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 中午11:03
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [foamliu/Transformer] 您好，文中的训练好的模型链接挂了，能重新分享一下吗 (#3)





 
***@***.***

**Comment by foamliu** [comment]
https://github.com/foamliu/Transformer/releases/tag/v1.0
